//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IHostingService")]
public interface IHostingService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHostingService/GetSelfhostInformation", ReplyAction="http://tempuri.org/IHostingService/GetSelfhostInformationResponse")]
    string[] GetSelfhostInformation();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHostingService/GetSelfhostInformation", ReplyAction="http://tempuri.org/IHostingService/GetSelfhostInformationResponse")]
    System.Threading.Tasks.Task<string[]> GetSelfhostInformationAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHostingService/GetSvcUtilInformation", ReplyAction="http://tempuri.org/IHostingService/GetSvcUtilInformationResponse")]
    string[] GetSvcUtilInformation();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHostingService/GetSvcUtilInformation", ReplyAction="http://tempuri.org/IHostingService/GetSvcUtilInformationResponse")]
    System.Threading.Tasks.Task<string[]> GetSvcUtilInformationAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHostingService/GetIISHostingInformation", ReplyAction="http://tempuri.org/IHostingService/GetIISHostingInformationResponse")]
    string[] GetIISHostingInformation();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHostingService/GetIISHostingInformation", ReplyAction="http://tempuri.org/IHostingService/GetIISHostingInformationResponse")]
    System.Threading.Tasks.Task<string[]> GetIISHostingInformationAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHostingService/GetWindowsServiceHostingInformation", ReplyAction="http://tempuri.org/IHostingService/GetWindowsServiceHostingInformationResponse")]
    string[] GetWindowsServiceHostingInformation();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHostingService/GetWindowsServiceHostingInformation", ReplyAction="http://tempuri.org/IHostingService/GetWindowsServiceHostingInformationResponse")]
    System.Threading.Tasks.Task<string[]> GetWindowsServiceHostingInformationAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IHostingServiceChannel : IHostingService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HostingServiceClient : System.ServiceModel.ClientBase<IHostingService>, IHostingService
{
    
    public HostingServiceClient()
    {
    }
    
    public HostingServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HostingServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HostingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HostingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string[] GetSelfhostInformation()
    {
        return base.Channel.GetSelfhostInformation();
    }
    
    public System.Threading.Tasks.Task<string[]> GetSelfhostInformationAsync()
    {
        return base.Channel.GetSelfhostInformationAsync();
    }
    
    public string[] GetSvcUtilInformation()
    {
        return base.Channel.GetSvcUtilInformation();
    }
    
    public System.Threading.Tasks.Task<string[]> GetSvcUtilInformationAsync()
    {
        return base.Channel.GetSvcUtilInformationAsync();
    }
    
    public string[] GetIISHostingInformation()
    {
        return base.Channel.GetIISHostingInformation();
    }
    
    public System.Threading.Tasks.Task<string[]> GetIISHostingInformationAsync()
    {
        return base.Channel.GetIISHostingInformationAsync();
    }
    
    public string[] GetWindowsServiceHostingInformation()
    {
        return base.Channel.GetWindowsServiceHostingInformation();
    }
    
    public System.Threading.Tasks.Task<string[]> GetWindowsServiceHostingInformationAsync()
    {
        return base.Channel.GetWindowsServiceHostingInformationAsync();
    }
}
